modLoader="javafml"
loaderVersion="[4,)"
license="${mod_license}"
issueTrackerURL="https://github.com/SeuUsuario/Whaleborne/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/SeuUsuario/Whaleborne"
logoFile="logo.png"
credits="FloofHips"
authors="${mod_authors}"
description="${mod_description}"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
